apiVersion: v1
kind: Pod
metadata:
  name: git-sync
  labels:
    app: sidecar
spec:
  initContainers:
  - name: ctr-sync
    restartPolicy: Always
    image: registry.k8s.io/git-sync/git-sync:v4.4.0
    volumeMounts:
    - name: html
      mountPath: /tmp/git
    env:
    - name: GITSYNC_REPO
      value: https://github.com/farshadmrd/TKB
    - name: GITSYNC_REF
      value: "2026"
    - name: GITSYNC_ROOT
      value: /tmp/git
    - name: GITSYNC_LINK
      value: html
    - name: GITSYNC_PERIOD
      value: 30s
  containers:
  - name: ctr-web
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/
  volumes:
  - name: html
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-sidecar
spec:
  selector:
    app: sidecar
  ports:
  - port: 80
  type: LoadBalancer
